### ISSUE TITLE
Switch database to PostgreSQL ?

### ISSUE THREAD

**Issue by bear454** [kubic-project/velum#111]
It looks like we're early enough in the project to switch to Postgres, instead of some version of MySQL.

Postgres, in general, is going to ensure a more stable environment (no risk of configuring with MyISAM ;-) - make deployment in other cloud services easier (like Heroku, for example), and ensure we have no licensing issues around 'community editions', etc., depending on how this project is eventually productized.

I'd be happy to submit a PR making the change.

**Comment by ereslibre** [comment]
I don't have a strong reason to say 'yes' or 'no' to this proposal. However we need to ensure that salt will properly work after this change and [our pillar overriding mechanism using our table will work as it did before](https://github.com/kubic-project/velum/blob/master/kubernetes/salt/config/master.d/salt-master.conf#L57-L79).

Other than that I don't really care about which relational DB we will be using (the Velum use case is not really demanding, so either relational DB will work just fine for us as far as I see it and as far as I can tell).

**Comment by robdaemon** [comment]
PostgreSQL is much more difficult to run as a stable, HA capable database inside of a Kubernetes cluster. We tried this at HPE in the Stackato product using pgPool II and had lots of stability problems.

I think, from an HA perspective, Percona XtraDB Clusters would work better. @SlickNik - want to chime in here with your experience?

I really do like PostgreSQL better as a database, but I'm afraid it's not ready to be used within a Kubernetes cluster.

I wouldn't mind seeing us support an external database, like Amazon RDS, etc, as opposed to switching the internal database.

**Comment by SlickNik** [comment]
To add to what @robdaemon said -- there are multiple tools (pgpool, pgbouncer, etc) that do query load balancing across multiple postgres instances, but really none of the postgres solutions support HA especially from a recovery perspective (i.e. the node which was down is now back online -- how do I add it back to the cluster?). Even stock MariaDB supports a Galera Cluster based HA solution, which supports this and will be a drop in replacement for what we have today.

**Comment by ereslibre** [comment]
I think given the experience and that we are already set with MariaDB we can close this issue... Are you OK with it @bear454?

**Comment by bear454** [comment]
You all have outlined a pretty clear reasoning for the database choice; I can't argue with that. The initial issue was filed under some assumptions that it turns out aren't true.

Thanks, guys, for the solid feedback.  I'm looking forward to contributing on the project.
