### ISSUE TITLE
Make configurable the IP/name for the "controller_node" 

### ISSUE THREAD

**Issue by inercia** [kubic-project/velum#123]
The machines in the cluster need to have some reference (ie, IP or DNS name) to the controller node. This is used, for example, for setting the salt minion configuration file with something like `master: <%= @controller_node %>`. 

We are currently setting this `@controller_node` from the IP/address obtained in Velum (from the remote end IP/name in the client's request), but this can change depending on how the user reached Velum.

We should:

* show this _reached_ name/IP as a suggested value for the `@controller_node`
* suggest to change it for a better name/IP, warning that it should be reachable by the rest of the machines in the cluster.

**Comment by ereslibre** [comment]
This has already been fixed by https://github.com/kubic-project/velum/pull/127
