### ISSUE TITLE
Allow users to download the ca.crt file

### ISSUE THREAD

**Issue by inercia** [kubic-project/velum#141]
Once the cluster has been deployed, users can currently download the `kubeconfig` file from the Dahboard. However, some users could also want to download the `ca.crt` file for connecting to `etcd` or the master in some other ways. We should show a link for downloading this `ca.crt` file from the Dashboard.

**Comment by stefsuse** [comment]
This appears to not be an issue. AFAIK kubectl from outside of the cluster works fine as is.
