### ISSUE TITLE
Not enough Workers to bootstrap. Please start at least one worker.

### ISSUE THREAD

**Issue by ereslibre** [kubic-project/velum#19]
This error gets triggered by `Minion.where(role: nil).count > 1` on `nodes_controller.rb:25` explicitly, but we should avoid this check here and just rescue from `Minion::NotEnoughMinions` when calling `Minion.assign_roles`.

**Comment by jimmykarily** [comment]
Using exceptions for flow control is considered an anti-pattern. If we know that something might fail we should check. This way we keep exceptions for really exceptional cases (as in, cases which we didn't predict).

**Comment by ereslibre** [comment]
OTOH if we change the minimal constraints that the cluster needs to start we have to update this logic on two different places. The already raised exception can be captured instead of doing an extra check.
