### ISSUE TITLE
Add `.phantomjs-version` file to the root of the project

### ISSUE THREAD

**Issue by ereslibre** [kubic-project/velum#202]
We can make [`caasp-devenv`](https://github.com/kubic-project/caasp-devenv/blob/5d926c72c5a0f6d4408f7e9f39defcda81550c6f/start#L98-L102) use the specified PhantomJS version specified on this file, as well as the [travis configuration can take it](https://github.com/kubic-project/velum/pull/199/files).

**Comment by mssola** [comment]
Just to not clutter the root of the project, we can have this file in another directory like `config`.

**Comment by ereslibre** [comment]
@mssola Sure, `config` sounds like a nice place too, I was suggesting creating it as a dot file in the root though, so it's next to `.rubocop.yml`, `.ruby-version`, `.codeclimate.yml`, `.travis.yml`... To follow the convention of `.ruby-version` it could be named `.phantomjs-version`.

I don't have a strong opinion on whether it should go inside `config` or the root folder, but it looks to me like the root project directory as a dot file is a very common place, so I have slight preference for the root dir, but if you think `config` fits better, `config` be it :smile:

**Comment by stefsuse** [comment]
this is resolved. the version is locked in .travis and in the development dockerfile
