### ISSUE TITLE
spinner on 'Accept Node'?

### ISSUE THREAD

**Issue by PI-Victor** [kubic-project/velum#228]
I know it's feature freeze, but i was wondering if we can add like a spinner for `Accept Node`. 
![giphy](https://user-images.githubusercontent.com/6294120/27822278-66d5d090-60a5-11e7-9f18-a6c3ab2b4dca.gif)

Mostly because it takes some time for the node to move to `nodes found` and it doesn't let me know if it's doing something. I'm just looking at it and i have the impulse to keep clicking `Accept node`.
I think it would be better to have some feedback, even if it's a short operation.

**Comment by vitoravelino** [comment]
There's already a [bug](https://bugzilla.suse.com/show_bug.cgi?id=1046663) regarding this. I didn't work on it yet because there are still some unknowns on how to solve the slowness issues we are currently having with salt and stuff.
