### ISSUE TITLE
lore ipsum dead code?

### ISSUE THREAD

**Issue by PI-Victor** [kubic-project/velum#240]
can someone tell me what diz little piece of code does and if it can it be removed?
https://github.com/kubic-project/velum/blob/master/app/views/setup/worker_bootstrap.html.slim#L2-L8
i have trouble understanding what exactly it's doing there, and why it's lore ipsum.
cc @mssola @ereslibre @vitoravelino

**Comment by vitoravelino** [comment]
It can be removed.
