### ISSUE TITLE
Do not hardcode product name

### ISSUE THREAD

**Issue by cwickert** [kubic-project/velum#266]
I noticed the product name 'CaaSP' is hardcoded in various places. This name is not to be used (in public), it's 'CaaS Platform' now. Given that this may change again, we better not hardcode it. I would even suggest to not hardcode 'SUSE' either.

**Comment by stefsuse** [comment]
I think this has been addressed some time ago. At least, my most recent development image has CaaS Platform branding. I will close this stale issue for now.
