### ISSUE TITLE
Can't change the velum admin user password

### ISSUE THREAD

**Issue by greygoo** [kubic-project/velum#327]
I seem not to find a way to change the password for the admin user in velum. IS that possible, and if it is - how can it be done?

**Comment by MaximilianMeister** [comment]
it is possible through the rails console

```
# in a containerized env
docker exec -it $(docker ps -a | grep velum-dashboard | awk '{print $1}') entrypoint.sh bundle exec rails c
u=User.where(:email => 'USER@EXAMPLE-MAIL.ORG').first
u.password='userpassword'
u.password_confirmation='userpassword'
u.save
```

**Comment by arjunm183** [comment]
This Doesnt help . Even after executing this with suse caas 2.0 version.

**Comment by stefsuse** [comment]
closing as this is for 2.0 and the issue now has workarounds and a better fix in progress
